import { Coin, CommentItem, UserRankInfo, WhaleTransaction, AdminConfig, RoadmapItem, PartnerItem } from './types';
import { generateInitialTradeFeed } from './utils/tradeGenerator';

export const USER_RANKS: UserRankInfo[] = [
  {
    title: 'Newbie Crypto',
    titleBn: 'Newbie Crypto',
    icon: '🌱',
    badgeColor: 'bg-slate-700 text-slate-200 border-slate-600',
    minPoints: 0,
  },
  {
    title: 'Bronze Staker',
    titleBn: 'Bronze Staker',
    icon: '🥉',
    badgeColor: 'bg-amber-950 text-amber-300 border-amber-700',
    minPoints: 200,
  },
  {
    title: 'Silver Staker',
    titleBn: 'Silver Staker',
    icon: '🥈',
    badgeColor: 'bg-slate-300 text-slate-900 border-slate-100 font-semibold',
    minPoints: 1000,
  },
  {
    title: 'Gold Hodler',
    titleBn: 'Gold Hodler',
    icon: '🥇',
    badgeColor: 'bg-yellow-500/20 text-yellow-300 border-yellow-500/50 font-bold',
    minPoints: 3000,
  },
  {
    title: 'Diamond Whale',
    titleBn: 'Diamond Whale',
    icon: '💎',
    badgeColor: 'bg-cyan-500/20 text-cyan-300 border-cyan-400 font-extrabold',
    minPoints: 10000,
  },
  {
    title: 'Master Ambassador',
    titleBn: 'Master Ambassador',
    icon: '👑',
    badgeColor: 'bg-purple-500/20 text-purple-300 border-purple-400 font-extrabold animate-pulse',
    minPoints: 25000,
  },
];

export const INITIAL_COINS: Coin[] = [
  {
    id: 'coin_live',
    name: '',
    symbol: '',
    description: '',
    descriptionBn: '',
    logoUrl: 'https://images.unsplash.com/photo-1622979135225-d2ba269bc1bd?auto=format&fit=crop&w=120&q=80',
    priceUsd: 0,
    priceBtc: 0,
    priceNative: 0,
    nativeSymbol: 'SOL',
    marketCapUsd: 0,
    volume24hUsd: 0,
    volume6hUsd: 0,
    volume1hUsd: 0,
    volume5mUsd: 0,
    priceChange5m: 0,
    priceChange1h: 0,
    priceChange6h: 0,
    priceChange24h: 0,
    priceChange7d: 0,
    circulatingSupply: 0,
    totalSupply: 0,
    allTimeHighUsd: 0,
    holdersCount: 0,
    liquidityUsd: 0,
    buys24h: 0,
    sells24h: 0,
    bullishPercentage: 50,
    dexScreenerUrl: '',
    pairAddress: '',
    chainId: '',
    dexName: '',
    lastSyncedAt: 'No Link Synced',
    auditStatus: 'Verified',
    websiteUrl: '',
    whitepaperUrl: '',
    githubUrl: '',
    telegramUrl: '',
    twitterUrl: '',
    contractAddresses: [],
    ipAddresses: [],
  },
];

export const INITIAL_ROADMAP: RoadmapItem[] = [
  {
    phase: 'Phase 1',
    title: 'Core Architecture & DexScreener Integration',
    titleBn: 'কোর আর্কিটেকচার ও ডেক্সস্ক্রিনার ইন্টিগ্রেশন',
    period: 'Q3 2026',
    status: 'completed',
    items: [
      'Token Smart Contract Deployment on Solana & BSC',
      'DexScreener Real-Time Live Data & Chart Sync API',
      'CertiK Audit Verification & IP Node Infrastructure setup',
      'Gamified Staking Vault & Point Reward Mechanism',
    ],
    itemsBn: [
      'সোলানা ও বিএসসিতে ট্রিপ টু কয়েন কন্ট্রাক্ট ডেপ্লয়মেন্ট',
      'ডেক্সস্ক্রিনার রিয়েল-টাইম লাইভ ডাটা ও ইন্টারঅ্যাক্টিভ চার্ট সিঙ্ক',
      'সার্টিক অডিট ভেরিফিকেশন ও গ্লোবাল আইপি নোড চালু',
      'পয়েন্ট রিওয়ার্ড সিস্টেম ও গ্যামিফাইড স্ট্যাকিং ভল্ট',
    ],
  },
  {
    phase: 'Phase 2',
    title: 'Travel Booking Utility & Web3 dApp Launch',
    titleBn: 'ট্রাভেল বুকিং ইউটিলিটি ও ড্যাপ উন্মোচন',
    period: 'Q4 2026',
    status: 'in_progress',
    items: [
      'TripToCoin Direct Flight & Hotel Booking dApp Integration',
      'Zero-Fee Travel Cashback Reward System using $TTC',
      'Cross-Chain Bridge Deployment (Solana ↔ BSC ↔ Ethereum)',
      'Tier 1 Centralized Exchange (CEX) Listings',
    ],
    itemsBn: [
      'ফ্লাইট ও হোটেল বুকিংয়ে ট্রিপ টু কয়েন পে-মেন্ট ইন্টিগ্রেশন',
      'TTC কয়েন ব্যবহারের মাধ্যমে জিরো-ফি ক্যাশব্যাক রিওয়ার্ড',
      'ক্রস-চেইন ব্রিজ ডেপ্লয়মেন্ট (সোলানা, বিএসসি ও ইথেরিয়াম)',
      'প্রথম সারির আন্তর্জাতিক সিইএক্স (CEX) এক্সচেঞ্জে লিস্টিং',
    ],
  },
  {
    phase: 'Phase 3',
    title: 'Global Partnerships & Physical Crypto Visa Cards',
    titleBn: 'গ্লোবাল পার্টনারশিপ ও ক্রিপ্টো ভিসা কার্ড',
    period: 'Q1-Q2 2027',
    status: 'upcoming',
    items: [
      'TripToCoin Web3 Crypto Debit/Visa Card for Airport Lounges',
      'Partnerships with International Airlines & Luxury Resort Chains',
      'Decentralized DAO Governance for Ecosystem Fund Allocations',
      '1,000,000+ Active Worldwide Community Milestone',
    ],
    itemsBn: [
      'এয়ারপোর্ট লাউঞ্জ ও ট্রাভেলে ব্যবহারের জন্য TTC ক্রিপ্টো ভিসা কার্ড',
      'আন্তর্জাতিক এয়ারলাইন্স ও লাক্সারি রিসোর্ট চেইনের সাথে পার্টনারশিপ',
      'কমিউনিটি ফান্ড ও প্রজেক্ট নিয়ন্ত্রণের জন্য DAO গভর্নেন্স',
      'বিশ্বজুড়ে ১০ লাখের বেশি অ্যাক্টিভ হোল্ডার ও ব্যবহারকারী অর্জন',
    ],
  },
];

export const INITIAL_PARTNERS: PartnerItem[] = [
  {
    id: 'p1',
    name: 'Raydium Protocol',
    category: 'DEX & Liquidity',
    logo: '⚡',
    status: 'Active Partner',
    description: 'Automated market maker and liquidity provider on Solana hosting the primary TTC pair.',
    descriptionBn: 'সোলানা নেটওয়ার্কের শীর্ষস্থান অধিকারকারী স্বয়ংক্রিয় মার্কেট মেকার এবং TTC-এর মূল লিকুইডিটি প্রদানকারী।',
  },
  {
    id: 'p2',
    name: 'DexScreener API Network',
    category: 'Cross-Chain Analytics',
    logo: '📊',
    status: 'Active Partner',
    description: 'Providing real-time live trading volume, price changes, buy/sell ratios, and candle chart feeds.',
    descriptionBn: 'রিয়েল-টাইম লাইভ ট্রেডিং ভলিউম, বাই/সেল রেশিও ও প্রাইস অ্যানালিটিক্স ডাটা সরবরাহকারী।',
  },
  {
    id: 'p3',
    name: 'Travala & Web3 Travel Alliance',
    category: 'Travel & Hospitality',
    logo: '✈️',
    status: 'In Discussion',
    description: 'Strategic integration for 2,200,000+ hotel properties & 600+ airlines accepting $TTC payments.',
    descriptionBn: 'বিশ্বব্যাপী ২২ লাখের বেশি হোটেল এবং ৬০০টি এয়ারলাইন্সে TTC পেমেন্ট সুবিধা চালু করার পরিকল্পনা।',
  },
  {
    id: 'p4',
    name: 'CertiK Blockchain Security',
    category: 'Security & Audit',
    logo: '🛡️',
    status: 'Active Partner',
    description: 'Continuous smart contract monitoring, threat scoring, and on-chain security verification.',
    descriptionBn: 'স্মার্ট কন্ট্রাক্ট অন-চেইন সিকিউরিটি, রিয়েল-টাইম থ্রেট মনিটরিং ও অডিট সার্টিফিকেশন।',
  },
  {
    id: 'p5',
    name: 'Phantom & Solana Foundation',
    category: 'Web3 Payments',
    logo: '🔮',
    status: 'Target Roadmap',
    description: 'Native mobile wallet integration for seamless 1-click travel payments.',
    descriptionBn: 'ওয়ান-ক্লিক ট্রাভেল পেমেন্টের জন্য প্যান্টম ও সোলানা নেটিভ ওয়ালেট ইন্টিগ্রেশন।',
  },
];

export const INITIAL_WHALES: WhaleTransaction[] = generateInitialTradeFeed(INITIAL_COINS[0], 25);

export const INITIAL_COMMENTS: CommentItem[] = [
  {
    id: 'c1',
    coinId: 'triptocoin',
    userId: 'u_admin',
    username: 'TripToCoin_Official',
    userRank: 'Master Ambassador',
    userPoints: 45000,
    text: 'Welcome to the official TripToCoin (TTC) team portal! We are syncing real live DEX data from DexScreener. Check out our verified Solana SPL contract (5pghkctym6odbhgo2tkmst2ajmjsb2uzbqrkkn4zuft5), node IPs, and project whitepaper below! 🚀✈️',
    sentiment: 'bullish',
    upvotes: 64,
    downvotes: 1,
    pinned: true,
    timestamp: '30 mins ago',
    replies: [
      {
        id: 'r1',
        commentId: 'c1',
        userId: 'u_2',
        username: 'CryptoRider_BD',
        userRank: 'Gold Hodler',
        userPoints: 4200,
        text: 'Showing exact live price now! Real DexScreener API integration works flawlessly. TripToCoin vision is super promising! ⚡',
        timestamp: '15 mins ago',
      },
    ],
  },
  {
    id: 'c2',
    coinId: 'triptocoin',
    userId: 'u_3',
    username: 'SolanaWhale99',
    userRank: 'Diamond Whale',
    userPoints: 14800,
    text: '75% bullish sentiment on DexScreener with $3.8M+ liquidity! The live buy/sell order flow is super clean.',
    sentiment: 'bullish',
    upvotes: 38,
    downvotes: 2,
    pinned: false,
    timestamp: '1 hour ago',
    replies: [],
  },
  {
    id: 'c3',
    coinId: 'triptocoin',
    userId: 'u_4',
    username: 'MetaTraveler',
    userRank: 'Silver Staker',
    userPoints: 2100,
    text: 'Just staked 2,500 TTC points into the vault! Eager for Phase 2 Web3 travel booking release.',
    sentiment: 'bullish',
    upvotes: 22,
    downvotes: 0,
    pinned: false,
    timestamp: '3 hours ago',
    replies: [],
  },
];

export const INITIAL_ADMIN_CONFIG: AdminConfig = {
  siteTitle: 'Crypto Analytics & DEX Portal',
  siteTitleBn: 'ক্রিপ্টো অ্যানালিটিক্স ও ডেক্স পোর্টাল',
  coinName: '',
  coinSymbol: '',
  dexScreenerUrl: '',
  stakingApyPercent: 18.5,
  dailyClaimPoints: 100,
  commentRewardPoints: 15,
  announcementBanner: '',
  announcementBannerBn: '',
  allowComments: true,
  autoSyncDexScreener: true,
};
